"""XYP2 source-reference contract generated by the JavaScript extension."""
import base64
from copy import deepcopy
from io import BytesIO
import json
from pathlib import Path

import pytest
from openpyxl import Workbook, load_workbook

from purchase_tool.procurement_import import ProcurementImportService, create_sales_source_key
from test_procurement_import import FakeSheetGateway, source_workbook, add_test_drawings, wait_for_sync

FIXTURE = json.loads((Path(__file__).parent / 'fixtures/source_associations.json').read_text(encoding='utf-8'))


def association_workbook(change=None, reverse=False):
    data = deepcopy(FIXTURE)
    payload = json.loads(data['remark'][6:-7])
    if change:
        change(payload, data)
    old = load_workbook(BytesIO(source_workbook()))
    headers = [cell.value for cell in old.active[1]]
    template = dict(zip(headers, next(old.active.iter_rows(min_row=2, max_row=2, values_only=True))))
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = 'order_'
    sheet.append(headers)
    for sales in data['sales'][::-1] if reverse else data['sales']:
        row = {**template, '店铺账号': data['order']['storeName'], '订单号': data['order']['platformOrderNo'],
               '包裹号': data['order']['packageId'], '订单金额': data['order']['salesAmount'],
               'SKU': sales['sku'], '产品规格': 'YDB--87654321-181:' + sales['variant'],
               '单个产品数量': sales['quantity'], '产品售价': sales['unitPrice'],
               '产品图片网址': sales['image'], '客服备注': '[XYP2]' + json.dumps(payload, ensure_ascii=False) + '[/XYP2]'}
        sheet.append([row[name] for name in headers])
    output = BytesIO()
    workbook.save(output)
    return add_test_drawings(output.getvalue(), [2, 3])


def parse(change=None, reverse=False):
    service = ProcurementImportService(sheet_gateway=FakeSheetGateway(), sleep_fn=lambda _: None)
    result = service.parse('association.xlsx', base64.b64encode(association_workbook(change, reverse)).decode())
    return service, result, service.pending[result['planId']]


@pytest.mark.parametrize('reverse', [False, True])
def test_javascript_references_keep_amounts_images_and_purchase_fields_across_row_order(reverse):
    _, result, plan = parse(reverse=reverse)
    assert result['canImport'] and result['errorCount'] == result['warningCount'] == 0
    assert result['detailCount'] == 4
    assert [row.item_sales_amount for row in plan.rows] == [200, 150, None, None]
    assert [row.order_image_url for row in plan.rows] == [FIXTURE['sales'][1]['image'], FIXTURE['sales'][0]['image'], FIXTURE['sales'][0]['image'], '']
    assert [row.values['需求数量'] for row in plan.rows] == [2, 1, 3, 1]
    assert all(row.values['主规格'] == 'Multicolor' and row.values['次规格'] == 'Set' for row in plan.rows)
    assert [row.values['销售订单金额'] for row in plan.rows] == [350, None, None, None]
    assert not plan.rows[2].source_unmatched
    assert plan.rows[3].source_unmatched
    for product in FIXTURE['products']:
        assert create_sales_source_key(product['sourceRef']['sku'], product['variant']) == product['sourceRef']['key']


@pytest.mark.parametrize('owner', [0, 1])
def test_missing_or_duplicate_amount_owner_does_not_duplicate_or_guess_money(owner):
    def change(payload, _data):
        payload['i'][1][10][1] = owner
        payload['i'][2][10][1] = owner
    _, result, plan = parse(change)
    assert result['canImport'] and result['errorCount'] == 0
    assert [row.item_sales_amount for row in plan.rows] == [200, None, None, None]
    assert plan.rows[1].order_image == plan.rows[2].order_image
    assert plan.rows[1].order_image
    assert result['warningCount'] == 2


@pytest.mark.parametrize('invalid', ['scope', 'version', 'missing_ref', 'quantity'])
def test_invalid_or_stale_explicit_associations_never_fall_back_to_purchase_specs(invalid):
    def change(payload, data):
        if invalid == 'scope':
            data['order']['packageId'] += 'OTHER'
        elif invalid == 'version':
            payload['a'][0] = 99
        elif invalid == 'missing_ref':
            payload['i'][1].pop()
        else:
            data['sales'][0]['quantity'] = 2
    _, result, plan = parse(change)
    assert result['canImport'] and result['errorCount'] == 0
    assert result['warningCount'] > 0
    assert plan.rows[1].item_sales_amount is None
    assert plan.rows[1].source_unmatched and not plan.rows[1].order_image
    assert plan.rows[1].values['需求数量'] == 1
    assert plan.rows[2].values['需求数量'] == 3


def test_changed_purchase_links_do_not_rewrite_confirmed_sales_relation():
    def change(payload, _data):
        for item in payload['i']:
            item[0:2] = ['ENTIRELY-DIFFERENT-PURCHASE', '1234567']
            item[4:6] = ['Any color', 'Any size']
    _, result, plan = parse(change)
    assert result['canImport'] and result['warningCount'] == 0
    assert [row.item_sales_amount for row in plan.rows] == [200, 150, None, None]
    assert all('goods_id=1234567' in row.values['采购链接'] for row in plan.rows)


def test_explicit_split_import_and_retry_share_images_without_duplicate_money_or_rows():
    service, result, plan = parse()
    service.validate_target(plan.plan_id, 'https://tenant.feishu.cn/sheets/SheetToken123', 'sheetA')
    started = service.start_sheet_sync(plan.plan_id, confirm_write=True)
    status = wait_for_sync(service, started['jobId'])
    assert status['state'] == 'completed', status
    assert status['written'] == 3 and status['skippedUnmatched'] == 1
    assert status['rowsWritten'] == 4
    existing = deepcopy(service.sheet_gateway.rows)
    started = service.start_sheet_sync(plan.plan_id, confirm_write=True)
    status = wait_for_sync(service, started['jobId'])
    assert status['rowsWritten'] == 0
    assert service.sheet_gateway.rows == existing
