# GENERATED by deploy/sync_environment_plan_core.py.
# Edit src/purchase_tool/env_batch.py instead.
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import re
from urllib.parse import parse_qsl, unquote, urlsplit

from .environment_plan_redaction import mask_email, scrub_text

SITE_ALIASES = {'MX': '希音墨西哥站', 'US': '希音美国站'}

SUPPORTED_SITES = frozenset(SITE_ALIASES)

EMAIL_RE = re.compile('^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$')

ORDER_RE = re.compile('(?:[?&])orderNo=([0-9a-f]+)(?:[&#]|$)', re.I)

EMAIL_KEY_PATH = '/api/boobar-graph'

MAIL_KEY_PATH = '/api'

VENDOR_TEMPLATE_HEADERS = ('邮箱账号', '密码', '接码Key链接', 'Cookie')

VENDOR_HEADER_ALIASES = (frozenset({'邮箱', '邮箱账号', '邮箱地址', '账号邮箱', '账号', 'email', 'emailaddress', 'buyeremail', 'buyeremailaddress', 'accountemail'}), frozenset({'密码', '账号密码', '登录密码', 'password', 'accountpassword'}), frozenset({'接码key', '接码key链接', '接码链接', '接码url', '验证码链接', '邮箱接码key', 'verificationurl', 'verificationcodeurl', 'keyurl'}), frozenset({'cookie', 'cookies', 'cookiejson', '登录cookie', '登录cookies'}))

VENDOR_HEADER_TOKENS = frozenset().union(*VENDOR_HEADER_ALIASES)

class EnvBatchError(ValueError):
    pass

def normalize_env_site(value):
    site = str(value or 'MX').strip().upper()
    if site not in SUPPORTED_SITES:
        raise EnvBatchError('建环境站点仅支持 MX（墨西哥）或 US（美国）')
    return site

COOKIE_SITE_MARKERS = {'MX': 'shein.com.mx', 'US': 'us.shein.com'}

def detect_cookie_site(cookie_text):
    """从 Cookie 域名识别账号站点；无标记返回 None，双标记返回 'CONFLICT'。"""
    text = str(cookie_text or '')
    hits = {site for (site, marker) in COOKIE_SITE_MARKERS.items() if re.search(re.escape(marker), text, re.I)}
    if len(hits) > 1:
        return 'CONFLICT'
    return next(iter(hits)) if hits else None

def _format_row_ranges(row_numbers):
    numbers = sorted(set((int(number) for number in row_numbers)))
    if not numbers:
        return ''
    ranges = []
    start = previous = numbers[0]
    for number in numbers[1:]:
        if number == previous + 1:
            previous = number
            continue
        ranges.append((start, previous))
        start = previous = number
    ranges.append((start, previous))
    return '、'.join(('第%d行' % start if start == end else '第%d-%d行' % (start, end) for (start, end) in ranges))

def count_mixed_site_accounts(accounts):
    """统计同时携带 MX/US 登录域 Cookie 的账号，不返回任何凭证内容。"""
    return sum((detect_cookie_site(account.cookie_text) == 'CONFLICT' for account in accounts))

def validate_accounts_site(accounts, site, *, allow_mixed=False):
    """校验账号 Cookie 站点；可显式兼容同时包含所选站点的混合登录态。"""
    site = normalize_env_site(site)
    conflicts = []
    mismatches = []
    for account in accounts:
        detected = detect_cookie_site(account.cookie_text)
        if detected == 'CONFLICT':
            conflicts.append(account.row_number)
        elif detected is not None and detected != site:
            mismatches.append((account.row_number, detected))
    rejected_conflicts = [] if allow_mixed else conflicts
    if not rejected_conflicts and (not mismatches):
        return
    issue_rows = rejected_conflicts + [row_number for (row_number, _detected) in mismatches]
    details = []
    if rejected_conflicts:
        details.append('墨西哥与美国登录域混合 %d 行' % len(rejected_conflicts))
    if mismatches:
        detected_counts = {}
        for (_row_number, detected) in mismatches:
            detected_counts[detected] = detected_counts.get(detected, 0) + 1
        details.append('、'.join(('Cookie仅%s站、与所选%s站不一致 %d 行' % (detected, site, count) for (detected, count) in sorted(detected_counts.items()))))
    raise EnvBatchError('Cookie 站点校验失败：共 %d 行数据异常（%s），行号 %s；整批拒收' % (len(issue_rows), '；'.join(details), _format_row_ranges(issue_rows)))

@dataclass
class BuyerAccount:
    row_number: int
    email: str
    password: str
    key_url: str
    cookie_text: str
    order_no: str
    buyer: str = ''

    @property
    def safe_email(self):
        return mask_email(self.email)

    @property
    def account_id(self):
        return hashlib.sha256(self.email.strip().casefold().encode('utf-8')).hexdigest()

def _cell_text(value):
    return value if isinstance(value, str) else str(value)

def _header_token(value):
    return re.sub('[\\s_-]+', '', str(value or '').strip().casefold())

def extract_vendor_order_no(key_url, account_email):
    """Extract a vendor order number or derive a stable opaque reference.

    Legacy code links expose a hexadecimal ``orderNo``.  Some vendors instead
    deliver links whose identity is either ``id+email``, an ``email``/``mail``
    query parameter, or the account email in the final URL path segment.
    Those links do not contain a purchase order number, so use a SHA-256
    reference while keeping the existing hexadecimal remark and cross-group
    deduplication contract.  Email-only formats deliberately share the same
    reference even if a vendor moves the email between query and path.
    """
    try:
        parsed = urlsplit(key_url)
        hostname = parsed.hostname
    except ValueError as exc:
        raise EnvBatchError('接码Key链接参数格式无效') from exc
    if parsed.scheme.lower() not in ('http', 'https') or not hostname or parsed.username is not None or (parsed.password is not None) or parsed.fragment:
        raise EnvBatchError('接码Key链接不含可识别的号商单号')
    legacy = ORDER_RE.search('?' + parsed.query)
    if legacy:
        return legacy.group(1)
    values = None
    link_email = ''
    normalized_path = parsed.path.rstrip('/')
    if normalized_path in (EMAIL_KEY_PATH, MAIL_KEY_PATH):
        try:
            pairs = parse_qsl(parsed.query, keep_blank_values=True, strict_parsing=True)
        except ValueError as exc:
            raise EnvBatchError('接码Key链接参数格式无效') from exc
        values = {}
        for (name, value) in pairs:
            if name in values:
                raise EnvBatchError('接码Key链接参数重复')
            values[name] = value
        if normalized_path == EMAIL_KEY_PATH:
            if set(values) not in ({'email'}, {'id', 'email'}):
                raise EnvBatchError('接码Key链接参数不符合新号商格式')
            link_email = values['email'].strip()
        else:
            if set(values) != {'type', 'mail'} or values['type'].strip() != 'html':
                raise EnvBatchError('接码Key链接参数不符合新号商格式')
            link_email = values['mail'].strip()
    elif not parsed.query:
        raw_segments = parsed.path.rstrip('/').split('/')
        raw_segments = [segment for segment in raw_segments if segment]
        if len(raw_segments) < 2:
            raise EnvBatchError('接码Key链接不含可识别的号商单号')
        raw_email = raw_segments[-1]
        if re.search('%(?![0-9A-Fa-f]{2})', raw_email):
            raise EnvBatchError('接码Key链接路径编码无效')
        try:
            link_email = unquote(raw_email, encoding='utf-8', errors='strict').strip()
        except (UnicodeDecodeError, ValueError) as exc:
            raise EnvBatchError('接码Key链接路径编码无效') from exc
    else:
        raise EnvBatchError('接码Key链接不含可识别的号商单号')
    if not EMAIL_RE.fullmatch(link_email) or link_email.casefold() != account_email.strip().casefold():
        raise EnvBatchError('接码Key链接邮箱与账号邮箱不一致')
    if values is not None and 'id' in values:
        vendor_id = values['id'].strip()
        if not re.fullmatch('[A-Za-z0-9_-]{6,128}', vendor_id):
            raise EnvBatchError('接码Key链接 id 格式无效')
        material = 'id\x00%s\x00%s' % (hostname.casefold(), vendor_id)
    else:
        material = 'email\x00%s' % link_email.casefold()
    return hashlib.sha256(('xynigo-vendor-ref-v1\x00' + material).encode('utf-8')).hexdigest()

def _is_vendor_header(values, row_number):
    tokens = tuple((_header_token(value) for value in values[:4]))
    if all((token in aliases for (token, aliases) in zip(tokens, VENDOR_HEADER_ALIASES))):
        return True
    recognized_count = sum((token in VENDOR_HEADER_TOKENS for token in tokens))
    if tokens[0] in VENDOR_HEADER_TOKENS or recognized_count >= 2:
        raise EnvBatchError('第 %d 行疑似表头但名称或列序不匹配，必须为：%s' % (row_number, ' / '.join(VENDOR_TEMPLATE_HEADERS)))
    return False

def parse_vendor_workbook(source):
    """解析第一张工作表固定四列，兼容有表头或无表头。"""
    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise EnvBatchError('缺少 openpyxl，无法读取 xlsx') from exc
    try:
        workbook = load_workbook(source, read_only=True, data_only=True)
    except Exception as exc:
        raise EnvBatchError('xlsx 无法打开：%s' % scrub_text(exc)) from exc
    try:
        sheet = workbook.worksheets[0]
        accounts = []
        (seen_emails, seen_orders) = (set(), set())
        first_content_row = True
        for (row_number, raw_row) in enumerate(sheet.iter_rows(values_only=True), start=1):
            values = list(raw_row)
            if not any((value not in (None, '') for value in values)):
                continue
            extras = values[4:]
            if any((value not in (None, '') for value in extras)):
                raise EnvBatchError('第 %d 行第 5 列后存在非空数据，严格模式拒收' % row_number)
            values += [None] * max(0, 4 - len(values))
            (email_raw, password_raw, key_raw, cookie_raw) = values[:4]
            if first_content_row:
                first_content_row = False
                if _is_vendor_header(values[:4], row_number):
                    continue
            if any((value in (None, '') for value in (email_raw, password_raw, key_raw, cookie_raw))):
                raise EnvBatchError('第 %d 行缺少邮箱/密码/接码Key/Cookie 字段' % row_number)
            email = _cell_text(email_raw).strip()
            if len(email) > 320 or not EMAIL_RE.fullmatch(email):
                raise EnvBatchError('第 %d 行邮箱格式错误：%s' % (row_number, mask_email(email)))
            email_key = email.casefold()
            if email_key in seen_emails:
                raise EnvBatchError('第 %d 行邮箱重复：%s' % (row_number, mask_email(email)))
            seen_emails.add(email_key)
            key_url = _cell_text(key_raw).strip()
            if len(key_url) > 16384 or not re.match('^https?://', key_url, re.I):
                raise EnvBatchError('第 %d 行接码Key不是 http(s) URL：%s' % (row_number, mask_email(email)))
            try:
                order_no = extract_vendor_order_no(key_url, email)
            except EnvBatchError as exc:
                raise EnvBatchError('第 %d 行%s：%s' % (row_number, str(exc), mask_email(email))) from exc
            if len(order_no) > 128:
                raise EnvBatchError('第 %d 行号商单号过长：%s' % (row_number, mask_email(email)))
            if order_no.casefold() in seen_orders:
                raise EnvBatchError('第 %d 行号商单号重复：%s' % (row_number, mask_email(email)))
            seen_orders.add(order_no.casefold())
            cookie_text = _cell_text(cookie_raw)
            password = _cell_text(password_raw)
            if len(password) > 8192 or len(cookie_text) > 10 * 1024 * 1024:
                raise EnvBatchError('第 %d 行密码或 Cookie 内容过长：%s' % (row_number, mask_email(email)))
            try:
                parsed_cookie = json.loads(cookie_text)
            except Exception as exc:
                raise EnvBatchError('第 %d 行 Cookie 不是合法 JSON：%s' % (row_number, mask_email(email))) from exc
            if not isinstance(parsed_cookie, (list, dict)):
                raise EnvBatchError('第 %d 行 Cookie JSON 必须是数组或对象：%s' % (row_number, mask_email(email)))
            accounts.append(BuyerAccount(row_number=row_number, email=email, password=password, key_url=key_url, cookie_text=cookie_text, order_no=order_no))
        if not accounts:
            raise EnvBatchError('Sheet1 没有有效账号行')
        return accounts
    finally:
        workbook.close()

ENVIRONMENT_PLAN_ACCOUNT_KEYS = frozenset({'rowNumber', 'email', 'password', 'keyUrl', 'cookie', 'orderNo'})

def serialize_buyer_accounts(accounts):
    """Serialize a parsed workbook for authenticated encrypted transport.

    The returned structure is sensitive and must never be logged or returned
    to a browser.  It is used by the cloud plan vault and the encrypted
    cloud-to-executor task payload only.
    """
    return [{'rowNumber': int(account.row_number), 'email': str(account.email), 'password': str(account.password), 'keyUrl': str(account.key_url), 'cookie': str(account.cookie_text), 'orderNo': str(account.order_no)} for account in accounts]

def deserialize_buyer_accounts(items, site='MX'):
    """Strictly rebuild a cloud plan before handing it to HubStudio code."""
    if not isinstance(items, list) or not 1 <= len(items) <= 2000:
        raise EnvBatchError('云端解析计划账号数量无效，请重新上传 xlsx')
    accounts = []
    (seen_emails, seen_orders) = (set(), set())
    for (index, item) in enumerate(items, start=1):
        if not isinstance(item, dict) or set(item) != ENVIRONMENT_PLAN_ACCOUNT_KEYS:
            raise EnvBatchError('云端解析计划结构无效，请重新上传 xlsx')
        try:
            row_number = int(item['rowNumber'])
        except (TypeError, ValueError) as exc:
            raise EnvBatchError('云端解析计划行号无效，请重新上传 xlsx') from exc
        if row_number < 1:
            raise EnvBatchError('云端解析计划行号无效，请重新上传 xlsx')
        values = {key: item[key] for key in ('email', 'password', 'keyUrl', 'cookie', 'orderNo')}
        if any((not isinstance(value, str) for value in values.values())):
            raise EnvBatchError('云端解析计划字段类型无效，请重新上传 xlsx')
        email = values['email'].strip()
        password = values['password']
        key_url = values['keyUrl'].strip()
        cookie_text = values['cookie']
        order_no = values['orderNo'].strip()
        if len(email) > 320 or len(password) > 8192 or len(key_url) > 16384 or (len(cookie_text) > 10 * 1024 * 1024) or (not re.fullmatch('[0-9a-f]{1,128}', order_no, re.I)):
            raise EnvBatchError('云端解析计划字段长度或格式无效，请重新上传 xlsx')
        if not EMAIL_RE.fullmatch(email):
            raise EnvBatchError('云端解析计划邮箱格式无效，请重新上传 xlsx')
        email_key = email.casefold()
        if email_key in seen_emails:
            raise EnvBatchError('云端解析计划邮箱重复，请重新上传 xlsx')
        seen_emails.add(email_key)
        try:
            expected_order_no = extract_vendor_order_no(key_url, email)
        except EnvBatchError as exc:
            raise EnvBatchError('云端解析计划接码链接无效，请重新上传 xlsx') from exc
        if expected_order_no.casefold() != order_no.casefold():
            raise EnvBatchError('云端解析计划号商单号校验失败，请重新上传 xlsx')
        if order_no.casefold() in seen_orders:
            raise EnvBatchError('云端解析计划号商单号重复，请重新上传 xlsx')
        seen_orders.add(order_no.casefold())
        try:
            parsed_cookie = json.loads(cookie_text)
        except Exception as exc:
            raise EnvBatchError('云端解析计划 Cookie 无效，请重新上传 xlsx') from exc
        if not isinstance(parsed_cookie, (list, dict)):
            raise EnvBatchError('云端解析计划 Cookie 无效，请重新上传 xlsx')
        accounts.append(BuyerAccount(row_number=row_number, email=email, password=password, key_url=key_url, cookie_text=cookie_text, order_no=order_no))
    validate_accounts_site(accounts, site, allow_mixed=True)
    return accounts
