#!/usr/bin/env python3
"""Generate the cloud buyer-account parser from the canonical local parser.

Only pure workbook parsing and authenticated-plan serialization nodes are
copied.  HubStudio, filesystem and local executor code stay in the desktop
package.
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
LOCAL_ROOT = REPOSITORY_ROOT / "src" / "purchase_tool"
CLOUD_ROOT = Path(__file__).resolve().parents[1] / "src" / "xynigo_auth"

ASSIGNMENTS = {
    "SITE_ALIASES",
    "SUPPORTED_SITES",
    "COOKIE_SITE_MARKERS",
    "EMAIL_RE",
    "ORDER_RE",
    "EMAIL_KEY_PATH",
    "MAIL_KEY_PATH",
    "VENDOR_TEMPLATE_HEADERS",
    "VENDOR_HEADER_ALIASES",
    "VENDOR_HEADER_TOKENS",
    "ENVIRONMENT_PLAN_ACCOUNT_KEYS",
}
DEFINITIONS = {
    "EnvBatchError",
    "normalize_env_site",
    "detect_cookie_site",
    "_format_row_ranges",
    "count_mixed_site_accounts",
    "validate_accounts_site",
    "BuyerAccount",
    "_cell_text",
    "_header_token",
    "extract_vendor_order_no",
    "_is_vendor_header",
    "parse_vendor_workbook",
    "serialize_buyer_accounts",
    "deserialize_buyer_accounts",
}


def _assignment_name(node: ast.Assign) -> str | None:
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return None
    return node.targets[0].id


def _selected_source(source: str) -> str:
    tree = ast.parse(source)
    selected: list[ast.AST] = []
    seen: set[str] = set()
    for node in tree.body:
        name = None
        if isinstance(node, ast.Assign):
            name = _assignment_name(node)
            wanted = name in ASSIGNMENTS
        elif isinstance(node, (ast.ClassDef, ast.FunctionDef)):
            name = node.name
            wanted = name in DEFINITIONS
        else:
            wanted = False
        if wanted:
            selected.append(node)
            seen.add(str(name))
    missing = (ASSIGNMENTS | DEFINITIONS) - seen
    if missing:
        raise RuntimeError("missing canonical parser nodes: " + ", ".join(sorted(missing)))
    # ``ast.get_source_segment`` starts at ``class`` and therefore drops
    # decorators such as ``@dataclass``.  Unparsing preserves decorators and
    # gives deterministic generated output across both runtimes.
    return "\n\n".join(ast.unparse(node) for node in selected)


def sync() -> list[tuple[str, str]]:
    source = (LOCAL_ROOT / "env_batch.py").read_text(encoding="utf-8")
    body = _selected_source(source)
    header = """# GENERATED by deploy/sync_environment_plan_core.py.
# Edit src/purchase_tool/env_batch.py instead.
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import re
from urllib.parse import parse_qsl, unquote, urlsplit

from .environment_plan_redaction import mask_email, scrub_text

"""
    outputs = {
        "environment_plan_core.py": (header + body + "\n").encode("utf-8"),
        "environment_plan_redaction.py": (LOCAL_ROOT / "redaction.py").read_bytes(),
    }
    result = []
    for filename, payload in outputs.items():
        (CLOUD_ROOT / filename).write_bytes(payload)
        result.append((filename, hashlib.sha256(payload).hexdigest()))
    return result


def main() -> int:
    for filename, digest in sync():
        print(f"synced={filename} sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
