#!/usr/bin/env python3
"""Sync the canonical procurement-import parser into the cloud package.

The local and cloud runtimes intentionally share parsing, header validation,
idempotency and workbook generation.  Only their Sheet gateways differ:
``lark-cli --as user`` locally, tenant-identity OpenAPI in the cloud.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
LOCAL_ROOT = REPOSITORY_ROOT / "src" / "purchase_tool"
CLOUD_ROOT = Path(__file__).resolve().parents[1] / "src" / "xynigo_auth"


def sync() -> list[tuple[str, str]]:
    CLOUD_ROOT.mkdir(parents=True, exist_ok=True)
    parser_source = (LOCAL_ROOT / "procurement_import.py").read_text(encoding="utf-8")
    parser_source = parser_source.replace(
        "from .xlsx_cell_images import embed_cell_images",
        "from .procurement_import_xlsx import embed_cell_images",
    ).replace(
        "from .lark_sheet_sync import LarkCliSheetsGateway, LarkSheetSyncError",
        "from .procurement_import_sheet import FeishuSheetsGateway as LarkCliSheetsGateway, LarkSheetSyncError",
    )
    generated_header = (
        "# GENERATED by deploy/sync_procurement_import_core.py.\n"
        "# Edit src/purchase_tool/procurement_import.py instead.\n"
    )
    parser_payload = (generated_header + parser_source).encode("utf-8")
    xlsx_payload = (LOCAL_ROOT / "xlsx_cell_images.py").read_bytes()
    outputs = {
        "procurement_import_core.py": parser_payload,
        "procurement_import_xlsx.py": xlsx_payload,
    }
    result = []
    for filename, payload in outputs.items():
        (CLOUD_ROOT / filename).write_bytes(payload)
        result.append((filename, hashlib.sha256(payload).hexdigest()))
    return result


def main() -> int:
    for filename, digest in sync():
        print(f"synced={filename} sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
