server {
    listen 80;
    server_name xynigo.samforo.icu;

    root /www/wwwroot/xynigo.samforo.icu;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://$host$request_uri;
    }

    access_log /www/wwwlogs/xynigo.samforo.icu.log;
    error_log /www/wwwlogs/xynigo.samforo.icu.error.log;
}
